# monitoring/prometheus/prometheus.yml

global:
  scrape_interval: 15s
scrape_configs:

  - job_name: 'environmental_monitoring'

    static_configs:

      - targets: ['localhost:8000']

    metrics_path: '/metrics'